Create Buttons, Link with AnswerQuestionCard
abieber1408/capstone-project pull request #14
Opened 2023-04-05 14:12 UTC by abieber1408

2023-04-06 08:02 UTC, LuYujin9 reviewed
The Page works very good! I am so glad that, you are progressing so fast. I only fund some small points. I hope it can help. 😄

2023-04-06 08:02 UTC, LuYujin9 commented on components/QuestionButtons/index.js
> +    };
Paul said, this can be deleted 😄

2023-04-06 08:02 UTC, LuYujin9 commented on components/QuestionButtons/index.js
> +export default function  ButtonGrid ( ) {
Do your consider, the name of function and folder as "questions list" or with "link"?   Because there is no button, but links. 😸  And it will be better, when the two names are the same.

2023-04-06 08:02 UTC, LuYujin9 commented on pages/index.js
> +import TitleList from "../components/QuestionButtons/index";
Maybe it will be easier to unterstand, when the name is the same as the name of this component.

2023-04-06 08:02 UTC, LuYujin9 commented on pages/index.js
>        <Footing>QuizMe-QuestionCard</Footing>
your Heading and Footing are both H1, but it allows only one H1 in one Page.

2023-04-06 08:02 UTC, LuYujin9 commented on pages/index.js
> -        <Quiz/>
your Deleted the Quiz, which belongs to last user story. I am not sure, if there is a besser way to do it. e.g. create an other page. Would you like to ask Paul?

2023-04-06 08:02 UTC, LuYujin9 commented on pages/question/[id].js
> +    const router = useRouter()
line 1  and 6 can be deleted? because you don't use it .

2023-04-06 08:02 UTC, LuYujin9 commented on lib/subjects.js
> +  {
the "id" should't be the same as the others.

2023-04-06 08:02 UTC, LuYujin9 commented on components/QuestionButtons/index.js
> +            {[...Array(6)].map((_, index) => (
I am not sure, what is Array here. normally it should be from as a props.  But it works! 😊

2023-04-06 12:35 UTC, abieber1408 commented on components/QuestionButtons/index.js
> +    };
- I don#t understand this?

2023-04-06 12:35 UTC, abieber1408 commented on components/QuestionButtons/index.js
> +export default function  ButtonGrid ( ) {
I know, maybe I should consider it.

2023-04-06 12:42 UTC, abieber1408 commented on pages/index.js
>        <Footing>QuizMe-QuestionCard</Footing>
I fixed it.

2023-04-06 12:43 UTC, abieber1408 commented on pages/index.js
> -        <Quiz/>
Sure, I wil.

2023-04-07 10:48 UTC, abieber1408 commented on components/QuestionButtons/index.js
> +            {[...Array(6)].map((_, index) => (
The data from my array is set to 6 in this 
case, and corresponds to buttons that al linkt with them.  So every button corresponds to one array, from 0 to 5.

2023-04-07 20:55 UTC, augustinanders approved these changes
Overall looks good to me. Just one little suggestion you can implement with your next PR.

2023-04-07 20:55 UTC, augustinanders commented on lib/subjects.js
> +    video: " ",
maybe you can ask chat gbt to write better mock-data for you. I am sure it is better for QA to have different Questions.

2023-04-08 11:17 UTC, abieber1408 commented on lib/subjects.js
> +    video: " ",
Yes. I was thinking on that. Thank You.

2023-04-12 15:15 UTC, stefankorder requested changes
Looks good so far. Just one recommendation you should change.

2023-04-12 15:15 UTC, stefankorder commented on components/AnswerQuestionCard/ChangeAnswerQuestion.js
>    </div>
I would suggest using less `<div>` tags. You could also use semantic tags like `<article>` or `<section>` if really needed or you don't surround the child elements if no extra container is needed.

2023-04-12 16:08 UTC, abieber1408 commented on components/AnswerQuestionCard/ChangeAnswerQuestion.js
>    </div>
Yes. I was waiting for the suggestion. I had  hard time trying to thing how to.

2023-04-13 07:57 UTC, abieber1408 commented on components/AnswerQuestionCard/ChangeAnswerQuestion.js
>    </div>
I mean, thinking how to do it.

2023-04-13 10:33 UTC, nikokreissl reviewed
Great work, keep it up! 😊
I left some comments on lines of code where I am kind of sure that it is not 100% correct like this but if I am wrong let me know. 🙂

2023-04-13 10:33 UTC, nikokreissl commented on components/AnswerQuestionCard/ChangeAnswerQuestion.js
> +  <article>
I am not 100% sure but I think that an `article` tag should not wrap a `section` tag - the other way around should be fine. Maybe you can double check, I might be wrong 🙂

2023-04-13 10:33 UTC, nikokreissl commented on components/AnswerQuestionCard/ChangeAnswerQuestion.js
> +        <p>{data.question}<ButtonNextQuestion onClick={onNext}>back</ButtonNextQuestion></p>
Kind of the same here - I think `p` tags should not wrap buttons as far as I know.

2023-04-13 10:33 UTC, nikokreissl commented on components/AnswerQuestionCard/ChangeAnswerQuestion.js
> +  float: right;
I think `float` has no impact here since you are working with flexbox. Not exactly sure what you want to achieve but maybe `flex-direction` can solve your problem based on how much I know about float? 🙂

2023-04-13 10:33 UTC, nikokreissl commented on components/AnswerQuestionCard/ChangeAnswerQuestion.js
>    width: justify-center;
I think this is not a valid property at least I could not find anything about it - but maybe I am wrong 🙂

2023-04-13 10:33 UTC, nikokreissl commented on components/AnswerQuestionCard/ChangeAnswerQuestion.js
> +  float: right;
Same as above for float in flexbox. 🙂

2023-04-13 10:33 UTC, nikokreissl commented on components/QuestionButtons/index.js
> +    return <Quiz data={subjects[openId]} id={openId} onAnswered={onAnswered} onNext={onNext}></Quiz>;
If you are not using children as prop you don't need the closing tag but can make it self closing 🙂

2023-04-13 10:33 UTC, nikokreissl commented on components/QuestionButtons/index.js
> +       <h2>{newStarScore}</h2>
As far as I know should a h1 not wrap around a h2 but maybe I am wrong.

2023-04-13 10:33 UTC, nikokreissl commented on components/ResultContainer/StyledResultContainer.js
> +float: right;
Again float inside flexbox.

2023-04-13 10:33 UTC, nikokreissl commented on components/Topic/StyledTopic.js
> +float:left;
Again float inside flexbox.

2023-04-13 10:44 UTC, abieber1408 commented on components/QuestionButtons/index.js
> +    return <Quiz data={subjects[openId]} id={openId} onAnswered={onAnswered} onNext={onNext}></Quiz>;
You are write. Thank You.

2023-04-13 11:02 UTC, abieber1408 commented on components/Topic/StyledTopic.js
> +float:left;
It works.

2023-04-13 11:02 UTC, abieber1408 commented on components/ResultContainer/StyledResultContainer.js
> +float: right;
It works.

2023-04-13 11:03 UTC, abieber1408 commented on components/AnswerQuestionCard/ChangeAnswerQuestion.js
> +  float: right;
It works.

2023-04-13 11:04 UTC, abieber1408 commented on components/AnswerQuestionCard/ChangeAnswerQuestion.js
> +  float: right;
Flex-direction does not works alone.

2023-04-13 11:04 UTC, abieber1408 commented on components/AnswerQuestionCard/ChangeAnswerQuestion.js
> +        <p>{data.question}<ButtonNextQuestion onClick={onNext}>back</ButtonNextQuestion></p>
Tank you. I will consider this.

2023-04-13 11:06 UTC, merged